# Generated by Django 4.2.1 on 2023-05-21 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('artist_id', models.CharField(max_length=70, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TrackFeatures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acousticness', models.DecimalField(decimal_places=10, default=0, max_digits=15)),
                ('danceability', models.DecimalField(decimal_places=10, default=0, max_digits=15)),
                ('energy', models.DecimalField(decimal_places=10, default=0, max_digits=15)),
                ('instrumentalness', models.DecimalField(decimal_places=10, default=0, max_digits=15)),
                ('key', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('loudness', models.DecimalField(decimal_places=10, default=0, max_digits=15)),
                ('liveness', models.DecimalField(decimal_places=10, default=0, max_digits=15)),
                ('mode', models.DecimalField(decimal_places=10, default=0, max_digits=15)),
                ('speechiness', models.DecimalField(decimal_places=10, default=0, max_digits=15)),
                ('tempo', models.DecimalField(decimal_places=10, default=0, max_digits=15)),
                ('time_signature', models.DecimalField(decimal_places=10, default=0, max_digits=15)),
                ('valence', models.DecimalField(decimal_places=10, default=0, max_digits=15)),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('track_id', models.CharField(max_length=70, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('acousticness', models.DecimalField(decimal_places=10, default=0, max_digits=15)),
                ('danceability', models.DecimalField(decimal_places=10, default=0, max_digits=15)),
                ('energy', models.DecimalField(decimal_places=10, default=0, max_digits=15)),
                ('instrumentalness', models.DecimalField(decimal_places=10, default=0, max_digits=15)),
                ('key', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('loudness', models.DecimalField(decimal_places=10, default=0, max_digits=15)),
                ('liveness', models.DecimalField(decimal_places=10, default=0, max_digits=15)),
                ('mode', models.DecimalField(decimal_places=10, default=0, max_digits=15)),
                ('speechiness', models.DecimalField(decimal_places=10, default=0, max_digits=15)),
                ('tempo', models.DecimalField(decimal_places=10, default=0, max_digits=15)),
                ('time_signature', models.DecimalField(decimal_places=10, default=0, max_digits=15)),
                ('valence', models.DecimalField(decimal_places=10, default=0, max_digits=15)),
                ('artists', models.ManyToManyField(to='api.artist')),
            ],
        ),
        migrations.AddField(
            model_name='artist',
            name='genres',
            field=models.ManyToManyField(to='api.genre'),
        ),
    ]
