# Generated by Django 4.2.1 on 2023-05-21 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='simplyfied_name',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
    ]
