# Generated by Django 4.2.2 on 2023-06-10 15:31

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_genre_simplyfied_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClassificationModel",
            fields=[
                ("model_id", models.AutoField(primary_key=True, serialize=False)),
                ("model_name", models.CharField(max_length=70, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="ClassificationParameter",
            fields=[
                ("parameters_id", models.AutoField(primary_key=True, serialize=False)),
                ("model_parameters", jsonfield.fields.JSONField()),
                ("generation_date", models.DateTimeField(auto_now=True)),
                ("classes", models.ManyToManyField(to="api.genre")),
                (
                    "model_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.classificationmodel",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="TrackFeatures",
        ),
    ]
