# Generated by Django 4.2.2 on 2023-06-12 20:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_classificationmodel_classificationparameter_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="classificationparameter",
            old_name="model_id",
            new_name="model",
        ),
        migrations.RemoveField(
            model_name="classificationparameter",
            name="model_parameters",
        ),
    ]
