# Generated by Django 4.2.2 on 2023-06-13 13:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0004_rename_model_id_classificationparameter_model_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="classificationparameter",
            name="accuracy_score",
            field=models.DecimalField(decimal_places=10, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name="classificationparameter",
            name="balanced_accuracy_score",
            field=models.DecimalField(decimal_places=10, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name="classificationparameter",
            name="serialized_model_path",
            field=models.CharField(default="bad_path", max_length=150, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="classificationparameter",
            name="top_k_accuracy_score",
            field=models.DecimalField(decimal_places=10, max_digits=15, null=True),
        ),
    ]
