# Generated by Django 4.2.2 on 2023-06-13 13:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0006_alter_classificationparameter_accuracy_score_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="classificationparameter",
            name="accuracy_score",
            field=models.DecimalField(decimal_places=15, max_digits=25, null=True),
        ),
        migrations.AlterField(
            model_name="classificationparameter",
            name="balanced_accuracy_score",
            field=models.DecimalField(decimal_places=15, max_digits=25, null=True),
        ),
        migrations.AlterField(
            model_name="classificationparameter",
            name="top_k_accuracy_score",
            field=models.DecimalField(decimal_places=15, max_digits=25, null=True),
        ),
    ]
