# Generated by Django 4.2.2 on 2023-06-13 13:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0008_alter_classificationparameter_accuracy_score_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="classificationparameter",
            name="classes",
            field=models.ManyToManyField(null=True, to="api.genre"),
        ),
    ]
