# Generated by Django 4.2.2 on 2023-06-13 15:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0009_alter_classificationparameter_classes"),
    ]

    operations = [
        migrations.AddField(
            model_name="classificationparameter",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
    ]
